namespace MultiplexedRbac.Sample.Crm.Api.Context
{
    /// <summary>
    /// Holds the current demo ContextKey generated by seeding/reset.
    /// </summary>
    public sealed class DemoSeedState
    {
        public string? AccessContextKey { get; set; }
    }
}
